### ISSUE TITLE
Error 16 on MacOS

### ISSUE THREAD

**Issue by HazeXVIII** [zoogie/MSET9#16]
Hello,
I keep on receiving "Error 16: Unable to unmount SD card" on MacOS after entering python3 mset9.py into the terminal.

**Comment by TophattedWasTaken** [comment]
Please use mset9.command instead of mset9.py and see if that works.

**Comment by jdongg** [comment]
Just wanted to chime in that I'm experiencing this issue as well and the mset9.command script didn't work either. FWIW, I currently have python 3.9.6 installed. I saw on discord that someone was able to get it to work with mset9.command so I'm wondering if maybe the version of python matters beyond just 3.x?

**Comment by zoogie** [comment]
Please provide python version and macOS version.

**Comment by jdongg** [comment]
After a few hours of tinkering around, I was able to get it working by replacing line 92 in `mset9.py` with

`return subprocess.run(["diskutil", command, "force", dev], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode`

and I have Luma3ds working now. Maybe OP can try this if the `mset9.command` file still doesn't allow for unmounting.

I was using Python 3.9.18 and am on MacOS 13.2.1 when I ran into the issue.

**Comment by zoogie** [comment]
> Hello, I keep on receiving "Error 16: Unable to unmount SD card" on MacOS after entering python3 mset9.py into the terminal.

Can you try again after replacing the mset9.py on your sd card with this different mset9.py?: https://github.com/zoogie/MSET9/blob/main/out/mset9.py

Suggested by jdongg in this issue.
