### ISSUE TITLE
Can't seem to find the .zip folder for mac 

### ISSUE THREAD

**Issue by macguy299** [zoogie/MSET9#37]
Im using the 3ds hack guide and I got to the setup and when it said to download the release.zip folder, i could not find it anywhere for mac. Ive looked everywhere and used the quick search, yet i have found nothing. Im not sure what to do, and i tried to find an alternate link, and ive found nothing. If someone could solve this issue that would be great, as im trying to mod a clients ds and i just got this mac and im switching from windows and i dont know.

**Comment by Anonymous941** [comment]
It's the same .zip file for all platforms, see https://3ds.hacks.guide/installing-boot9strap-(mset9-cli)
