### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Lumaah** [zoogie/MSET9#6]
I'm having this error when i'm trying to Setup mset9

Traceback (most recent call last):
  File "F:\mset9.py", line 249, in <module>
    setup()
  File "F:\mset9.py", line 123, in setup
    assert(mii_ok==1)
AssertionError

**Comment by THZoria** [comment]
hello
You have not created the data in the mii makers app.
Run the mii maker string to create the data and try again, it should work.
