### ISSUE TITLE
problem with the combination to press when installing the FIRM

### ISSUE THREAD

**Issue by SimorzJ4F** [zoogie/MSET9#9]
ok so i tried so many times to do this but (i have followed this guide: https://3ds.hacks.guide/key-information) but when i get to the steps where i have to go to the settings > data manager > 3ds > extra data, look if there is the Mii thing, extract the sd card without touching any button, use the MSET9.py to inject trigger file 002F003A.txt (the option 2) and inserting back the sd card into my 3ds xl well, yes it does open the screen to install FIRM but when i have to press the combination nothing happens. the console is not freezed because i can still press "b" to cancel, but the combination does not want to be pressed
![a084d2e2-c0fa-4b38-936f-999952d6b623](https://github.com/zoogie/MSET9/assets/147660802/c0c31b1c-7cc3-4c40-95ee-6a812a38c9b6)

**Comment by TophattedWasTaken** [comment]
I think that's a SafeB9SInstaller issue, not MSET9. I'd ask on the [Nintendo Homebrew server](https://discord.com/invite/MWxPgEp)

**Comment by SimorzJ4F** [comment]
already tried asking..... they do not know the answer, or at least, they have confirmed that the console is not freezed and then no more responses

**Comment by SimorzJ4F** [comment]
idk what to do, is there something to be fixed, that i can fix or...?

**Comment by TophattedWasTaken** [comment]
I don't know in perfect honesty

**Comment by OasisAkari** [comment]
Sounds likely caused by a stuck button. Have you tested that all the buttons are working properly?

(Especially the SELECT and START buttons, you can open the internet browser on 3DS to test them)

**Comment by SimorzJ4F** [comment]
ok i found that i can press the left and right button a little bit harder and it works on the menu, i will try doing the hacking method and i'll see

**Comment by OasisAkari** [comment]
I build an OpenFirmInstaller (tried to build SafeB9Sinstaller but always end up getting FIRM crypto fail, dunno why :/) that removes the key combination, just press A to confirm the installation:

[G.zip](https://github.com/zoogie/MSET9/files/12879750/G.zip)

just unzip, overwrite to the root directory of the SD card and try the steps again

tested passed on my console, but use it own at your risk if the common methods still fail

**Comment by chronoss09** [comment]
First try and combinaison work, i thnik you have some problem with your 3ds !!!

**Comment by zoogie** [comment]
Seems Simorz is happy now.
